# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MarvelList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelList
  
  pod 'Alamofire', '~> 5.4.4'
  pod 'Kingfisher'
  pod 'SVProgressHUD'
  pod 'PromiseKit', '~> 6.8.4'

  target 'MarvelListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelListUITests' do
    # Pods for testing
  end

end
